//metal, glass, rod stacks
#define MAX_STACK_AMOUNT_METAL	50
#define MAX_STACK_AMOUNT_GLASS	50
#define MAX_STACK_AMOUNT_RODS	60

#define MATERIAL_AMOUNT_PER_SHEET 2000

// These are similar to SECOND/SECONDS where you just type out X MATERIAL_SHEET or X MATERIAL_SHEETS.
#define MATERIAL_SHEET * MATERIAL_AMOUNT_PER_SHEET
#define MATERIAL_SHEETS * MATERIAL_AMOUNT_PER_SHEET