// Radio frequencies.
#define FREQUENCY_COMMON 1459

#define FREQUENCY_COMMAND	1353 //command, colored gold in chat window
#define FREQUENCY_SYNDICATE 1213

// department channels
#define FREQUENCY_SECURITY		1359
#define FREQUENCY_ENGINEERING	1357
#define FREQUENCY_SCIENCE		1351
#define FREQUENCY_MEDICAL		1355
#define FREQUENCY_SUPPLY		1347
#define FREQUENCY_MINING		1349

#define FREQUENCY_AI 1447

// central command channels, i.e deathsquid & response teams
#define FREQUENCY_RESPONSETEAM	1345
#define FREQUENCY_DEATHSQUAD	1341
/var/list/CENT_FREQS = list(FREQUENCY_RESPONSETEAM, FREQUENCY_DEATHSQUAD)

//depenging helpers
/var/list/DEPT_FREQS = list(
	FREQUENCY_SCIENCE,
	FREQUENCY_MEDICAL,
	FREQUENCY_ENGINEERING,
	FREQUENCY_SECURITY,
	FREQUENCY_SYNDICATE,
	FREQUENCY_RESPONSETEAM,
	FREQUENCY_DEATHSQUAD,
	FREQUENCY_SUPPLY,
	FREQUENCY_MINING
)