#define SPECIAL_ROLE_ALIEN "alien"
#define SPECIAL_ROLE_CHANGELING "changeling"
#define SPECIAL_ROLE_CORTICAL_BORER "cortical borer"
#define SPECIAL_ROLE_CULTIST "cultist"
#define SPECIAL_ROLE_DEATH_COMMANDO "death commando"
#define SPECIAL_ROLE_HEAD_REVOLUTIONARY "head revolutionary"
#define SPECIAL_ROLE_LARVA "larva" // Not sure if this one's actually used but I'll figure that out later.
#define SPECIAL_ROLE_MALF_AI "malf ai"
#define SPECIAL_ROLE_NINJA "ninja"
#define SPECIAL_ROLE_RESPONSE_TEAM "response team"
#define SPECIAL_ROLE_REVOLUTIONARY "revolutionary"
#define SPECIAL_ROLE_SYNDICATE "syndicate"
#define SPECIAL_ROLE_SYNDICATE_COMMANDO "syndicate commando"
#define SPECIAL_ROLE_TRAITOR "traitor"
#define SPECIAL_ROLE_VOX_RAIDER "vox raider"
#define SPECIAL_ROLE_WISH_GRANTER_AVATAR "avatar of the wish granter"
#define SPECIAL_ROLE_WIZARD "wizard"