// Stat and verb panel names.
#define PANEL_STATUS "Status"
#define PANEL_CONTROLLERS "Controllers"
#define PANEL_PROCESSES "Processes"
#define PANEL_LOBBY "Lobby"
#define PANEL_ADMIN "Admin"
#define PANEL_DEBUG "Debug"
#define PANEL_FUN "Fun"
#define PANEL_IC "IC"
#define PANEL_MAPPING "Mapping"
#define PANEL_OOC "OOC"
#define PANEL_OBJECT "Object"
#define PANEL_PREFERENCES "Preferences"
#define PANEL_SERVER "Server"
#define PANEL_SPECIAL_VERBS "Special Verbs"
#define PANEL_ZAS "ZAS"