/proc/communications_blackout(silent = 1)
	if(!silent)
		command_alert("Ionospheric anomalies detected. Temporary telecommunication failure imminent. Please contact you-BZZT")
	else // AIs will always know if there's a comm blackout, rogue AIs could then lie about comm blackouts in the future while they shutdown comms
		for(var/mob/living/silicon/ai/A in GLOBL.player_list)
			to_chat(A, "<br>")
			to_chat(A, SPAN_DANGER("Ionospheric anomalies detected. Temporary telecommunication failure imminent. Please contact you-BZZT"))
			to_chat(A, "<br>")
	for_no_type_check(var/obj/machinery/telecoms/T, GLOBL.telecoms_list)
		T.emp_act(1)