/mob/living/silicon/pai/death(gibbed)
	if(isnotnull(card))
		card.removePersonality()
		if(gibbed)
			loc = GET_TURF(card)
			qdel(card)
	if(isnotnull(mind))
		qdel(mind)
	..(gibbed)
	ghostize()
	qdel(src)