#undef LIGHT_MODE_EMERGENCY

#undef LIGHT_STAGE_ONE
#undef LIGHT_STAGE_TWO
#undef LIGHT_STAGE_THREE

#undef LIGHT_OK
#undef LIGHT_EMPTY
#undef LIGHT_BROKEN
#undef LIGHT_BURNED

#undef LIGHT_POWER_FACTOR