#define MECHA_FLAG_RIPLEY BITFLAG(0) // Ripley, Firefighter
#define MECHA_FLAG_DEATH_RIPLEY BITFLAG(1)
#define MECHA_FLAG_RESCUE_RANGER BITFLAG(2)
#define MECHA_FLAG_SINDY BITFLAG(3)

#define MECHA_FLAG_HOVERPOD BITFLAG(4) // HoverPod, Shuttle HoverPod
#define MECHA_FLAG_COMBAT_HOVERPOD BITFLAG(5)

#define MECHA_FLAG_DREADNOUGHT BITFLAG(6)
#define MECHA_FLAG_BULWARK BITFLAG(7)

#define MECHA_FLAG_ODYSSEUS BITFLAG(8) // Odysseus, Dark Odysseus
#define MECHA_FLAG_EURYMACHUS BITFLAG(9)

#define MECHA_FLAG_GYGAX BITFLAG(10) // Gygax, Dark Gygax
#define MECHA_FLAG_SERENITY BITFLAG(11)

#define MECHA_FLAG_DURAND BITFLAG(12) // Durand, Archambeau
#define MECHA_FLAG_MARAUDER BITFLAG(13) // Marauder, Mauler, Seraph

#define MECHA_FLAG_PHAZON BITFLAG(14) // Phazon, Dark Phazon

#define MECHA_FLAG_HONK BITFLAG(15)
#define MECHA_FLAG_RETICENCE BITFLAG(16)

#define MECHA_FLAG_EIDOLON BITFLAG(17) // Eidolon, Salvaged Eidolon

#define MECHA_FLAG_WORKING (\
	MECHA_FLAG_RIPLEY | MECHA_FLAG_DEATH_RIPLEY | MECHA_FLAG_RESCUE_RANGER | MECHA_FLAG_SINDY |\
	MECHA_FLAG_HOVERPOD | MECHA_FLAG_COMBAT_HOVERPOD | MECHA_FLAG_DREADNOUGHT | MECHA_FLAG_BULWARK\
)

#define MECHA_FLAG_MEDICAL (\
	MECHA_FLAG_RESCUE_RANGER | MECHA_FLAG_ODYSSEUS | MECHA_FLAG_EURYMACHUS | MECHA_FLAG_SERENITY\
)

#define MECHA_FLAG_COMBAT (\
	MECHA_FLAG_DEATH_RIPLEY | MECHA_FLAG_SINDY | MECHA_FLAG_COMBAT_HOVERPOD | MECHA_FLAG_BULWARK | MECHA_FLAG_EURYMACHUS |\
	MECHA_FLAG_GYGAX | MECHA_FLAG_SERENITY | MECHA_FLAG_DURAND | MECHA_FLAG_MARAUDER | MECHA_FLAG_PHAZON |\
	MECHA_FLAG_HONK | MECHA_FLAG_RETICENCE | MECHA_FLAG_EIDOLON\
)