#define MECHA_MESSAGE_COOLDOWN 2 SECONDS

// Internal Damage
#define MECHA_INT_FIRE BITFLAG(0)
#define MECHA_INT_TEMP_CONTROL BITFLAG(1)
#define MECHA_INT_SHORT_CIRCUIT BITFLAG(2)
#define MECHA_INT_TANK_BREACH BITFLAG(3)
#define MECHA_INT_CONTROL_LOST BITFLAG(4)

// Equipment Range
#define MECHA_EQUIP_MELEE BITFLAG(0)
#define MECHA_EQUIP_RANGED BITFLAG(1)

// Mecha Type
#define MECHA_TYPE_RIPLEY BITFLAG(0) // Ripley, Firefighter
#define MECHA_TYPE_DEATH_RIPLEY BITFLAG(1)
#define MECHA_TYPE_RESCUE_RANGER BITFLAG(2)
#define MECHA_TYPE_SINDY BITFLAG(3)
#define MECHA_TYPE_PADDY BITFLAG(4)

#define MECHA_TYPE_HOVERPOD BITFLAG(5) // HoverPod, Shuttle HoverPod
#define MECHA_TYPE_COMBAT_HOVERPOD BITFLAG(6)

#define MECHA_TYPE_DREADNOUGHT BITFLAG(7)
#define MECHA_TYPE_BULWARK BITFLAG(8)

#define MECHA_TYPE_ODYSSEUS BITFLAG(9) // Odysseus, Dark Odysseus
#define MECHA_TYPE_EURYMACHUS BITFLAG(10)

#define MECHA_TYPE_GYGAX BITFLAG(11) // Gygax, Dark Gygax
#define MECHA_TYPE_SERENITY BITFLAG(12)

#define MECHA_TYPE_DURAND BITFLAG(13) // Durand, Archambeau
#define MECHA_TYPE_BRIGAND BITFLAG(14)
#define MECHA_TYPE_MARAUDER BITFLAG(15) // Marauder, Mauler, Seraph, Fiend

#define MECHA_TYPE_PHAZON BITFLAG(16) // Phazon, Dark Phazon

#define MECHA_TYPE_HONK BITFLAG(17)
#define MECHA_TYPE_RETICENCE BITFLAG(18)
#define MECHA_TYPE_JUSTICE BITFLAG(19)

#define MECHA_TYPE_EIDOLON BITFLAG(20) // Eidolon, Salvaged Eidolon

#define MECHA_TYPE_WORKING (\
	MECHA_TYPE_RIPLEY | MECHA_TYPE_DEATH_RIPLEY | MECHA_TYPE_RESCUE_RANGER | MECHA_TYPE_SINDY |\
	MECHA_TYPE_HOVERPOD | MECHA_TYPE_COMBAT_HOVERPOD | MECHA_TYPE_DREADNOUGHT | MECHA_TYPE_BULWARK\
)

#define MECHA_TYPE_MEDICAL (\
	MECHA_TYPE_RESCUE_RANGER | MECHA_TYPE_ODYSSEUS | MECHA_TYPE_EURYMACHUS | MECHA_TYPE_SERENITY\
)

#define MECHA_TYPE_COMBAT (\
	MECHA_TYPE_DEATH_RIPLEY | MECHA_TYPE_SINDY | MECHA_TYPE_PADDY | MECHA_TYPE_COMBAT_HOVERPOD | MECHA_TYPE_BULWARK |\
	MECHA_TYPE_EURYMACHUS | MECHA_TYPE_GYGAX | MECHA_TYPE_SERENITY | MECHA_TYPE_DURAND | MECHA_TYPE_BRIGAND |\
	MECHA_TYPE_MARAUDER | MECHA_TYPE_PHAZON | MECHA_TYPE_HONK | MECHA_TYPE_RETICENCE | MECHA_TYPE_EIDOLON\
)